name: "GitHub Issue Status Notifier"
description: "Sends GitHub repo status and tasks to a specified service via API."
author: "status-ai"
inputs:
  github_token:
    description: "GitHub API token"
    required: true
  repo_name:
    description: "GitHub repository name"
    required: true
  repo_owner:
    description: "GitHub repository owner"
    required: true
  slack_user_token:
    description: "Slack user token"
    required: false
  lookback_days:
    description: "Number of days to look back for issues"
    default: "3"
  slack_team_id:
    description: "Slack team ID"
    required: false
  slack_webhook_url:
    description: "Slack webhook URL"
    required: false
  recipients:
    description: "Comma-separated list of email recipients"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"