name: "GitHub Issue Status Notifier"
description: "Sends GitHub repo status and tasks to a specified service via API."
author: "status-ai"
inputs:
  repo_name:
    description: "GitHub repository name"
    required: true
  repo_owner:
    description: "GitHub repository owner"
    required: true
  lookback_days:
    description: "Number of days to look back for issues"
    default: 3
  slack_team_id:
    description: "Slack team ID"
    required: false
  recipients:
    description: "Comma-separated list of email recipients"
    required: false
env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  SLACK_USER_TOKEN: ${{ secrets.SLACK_USER_TOKEN }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
runs:
  using: "docker"
  image: "Dockerfile"
