name: "GitHub Issue Status Notifier"
description: "Sends GitHub repo status and tasks to a specified service via API."
author: "status-ai"
inputs:
  repo_name:
    description: "GitHub repository name"
    required: true
  repo_owner:
    description: "GitHub repository owner"
    required: true
  
  slack_team_id:
    description: "Slack team ID"
    required: false
  recipients:
    description: "Comma-separated list of email recipients"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
