name: Get repo status

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "GitHub repository name"
        required: true
        default: "my-repo"      # Change as needed
      repo_owner:
        description: "GitHub repository owner"
        required: true
        default: "my-owner"     # Change as needed
      lookback_days:
        description: "Number of days to look back for issues"
        required: false
        default: "3"
      recipients:
        description: "Comma-separated list of email recipients"
        required: false

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Custom Action to Send Secrets to My App
        uses: ./.github/actions/runstatus-action
        with:
          repo_name: ${{ github.event.inputs.repo_name }}
          repo_owner: ${{ github.event.inputs.repo_owner }}
          lookback_days: ${{ github.event.inputs.lookback_days }}
          recipients: ${{ github.event.inputs.recipients }}
