name: Get repo status

on:
  workflow_dispatch:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Custom Action to Send Secrets to My App
      
        uses: ./.github/actions/runstatus-action
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          repo_name: ${{ vars.REPO_NAME }}
          repo_owner: ${{ vars.REPO_OWNER }}
          slack_user_token: ${{ secrets.SLACK_USER_TOKEN }}
          lookback_days: ${{ vars.LOOKBACK_DAYS }}
          slack_team_id: ${{ secrets.SLACK_TEAM_ID }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          recipients: ${{ vars.RECIPIENTS }}