name: Get repo status

on:
  workflow_dispatch:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send secrets to my-app.com
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_NAME: ${{  vars.REPO_NAME }}
          REPO_OWNER: ${{ vars.REPO_OWNER }}  
          SLACK_USER_TOKEN: ${{ secrets.SLACK_USER_TOKEN }}
          LOOKBACK_DAYS: ${{ vars.LOOKBACK_DAYS }}
          SLACK_TEAM_ID: ${{ secrets.SLACK_TEAM_ID }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 
          RECIPIENTS: ${{ vars.RECIPIENTS }}
          
          
          
          
          
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "github_token": "'"$GITHUB_TOKEN"'",
              "repo_name": "'"$REPO_NAME"'",
              "repo_owner": "'"$REPO_OWNER"'",
              "slack_user_token": "'"$SLACK_USER_TOKEN"'",
              "lookback_days": '$LOOKBACK_DAYS',
              "slack_team_id": "'"$SLACK_TEAM_ID"'",
              "slack_webhook_url": "'"$SLACK_WEBHOOK_URL"'",
              "to_email": '"$RECIPIENTS"'
              
              
              
              
            }' \
            https://runstatus.dev/api/v0/status
