name: Get repo status

on:
  workflow_dispatch:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print recipients to debug
        run: echo ${{ vars.RECIPIENTS }}

      - name: Run Custom Action to Send Secrets to My App
  
        uses: ./.github/actions/runstatus-action
        env:  # Use `env` to set environment variables
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_NAME: ${{ vars.REPO_NAME }}
          REPO_OWNER: ${{ vars.REPO_OWNER }}
          SLACK_USER_TOKEN: ${{ secrets.SLACK_USER_TOKEN }}
          LOOKBACK_DAYS: ${{ vars.LOOKBACK_DAYS }}
          SLACK_TEAM_ID: ${{ secrets.SLACK_TEAM_ID }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          RECIPIENTS: ${{ vars.RECIPIENTS }} 